name: bridgelog_app
description: BridgeLog - MVP
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.0
  geolocator: ^10.1.0
  image_picker: ^1.1.2 
  file_picker: ^8.0.1   
  intl: ^0.19.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

